### ISSUE TITLE
GeckoView on Android Wear

### ISSUE THREAD

**Issue by yschimke** [mozilla/geckoview#173]
Blank activity sample app, followed https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/geckoview-quick-start.html

```
2021-10-13 08:23:17.824 20490-20542/com.google.wear.geckoview E/GeckoLibLoad: Load sqlite start
2021-10-13 08:23:17.824 20490-20542/com.google.wear.geckoview E/GeckoLibLoad: Couldn't get a handle to libnss3!
2021-10-13 08:23:17.824 20490-20542/com.google.wear.geckoview E/GeckoLibLoad: Throw
2021-10-13 08:23:17.825 20490-20542/com.google.wear.geckoview E/GeckoLibLoad: Load sqlite done
2021-10-13 08:23:17.831 20490-20542/com.google.wear.geckoview E/AndroidRuntime: FATAL EXCEPTION: Gecko
    Process: com.google.wear.geckoview, PID: 20490
    java.lang.Exception: Error loading sqlite libraries
        at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibsNative(Native Method)
        at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibs(GeckoLoader.java:200)
        at org.mozilla.gecko.GeckoThread.loadGeckoLibs(GeckoThread.java:269)
        at org.mozilla.gecko.GeckoThread.initGeckoEnvironment(GeckoThread.java:289)
        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:448)
2021-10-13 08:23:17.991 782-5532/system_process W/ActivityManager:   Force finishing activity com.google.wear.geckoview/.MainActivity
```

**Comment by yschimke** [comment]
Launches with android:extractNativeLibs="true"

**Comment by yschimke** [comment]
Getting blank view, but not sure why.

**Comment by yschimke** [comment]
Works with 93.0.20210927210923 stable, the example in the docs is a night version 70.
