### ISSUE TITLE
GeckoView error occurred, Using App Bundle in GooglePlay

### ISSUE THREAD

**Issue by ifmvo** [mozilla/geckoview#79]
### Hello, I used GeckoView in my Android app.
`Implementation 'org.mozilla.geckoview:geckoview-beta:69.0.20190808090046'`
`abiFilters "armeabi-v7a", "arm64-v8a"`

### Using App Bundle in GooglePlay, an error occurred

```
Load sqlite start
Couldn't get a handle to libnss3!
Throw
Load sqlite done
>>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 6519 ("Gecko")
java.lang.Exception: Error loading sqlite libraries
    at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibsNative(Native Method)
    at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibs(GeckoLoader.java:250)
    at org.mozilla.gecko.GeckoThread.initGeckoEnvironment(GeckoThread.java:114)
    at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:165)
Main thread (1) stack:
    android.os.BinderProxy.transactNative(Native Method)
    android.os.BinderProxy.transact(Binder.java:496)
    com.android.internal.view.IInputMethodManager$Stub$Proxy.windowGainedFocus(IInputMethodManager.java:730)
    android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1230)
    android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1447)
    android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3423)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5595)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Error getting package info
android.content.pm.PackageManager$NameNotFoundException: org.mozilla.fennec
    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:123)
    at org.mozilla.gecko.CrashHandler.getCrashExtras(CrashHandler.java:234)
    at org.mozilla.gecko.GeckoAppShell$1.getCrashExtras(GeckoAppShell.java:143)
    at org.mozilla.gecko.CrashHandler.reportException(CrashHandler.java:377)
    at org.mozilla.gecko.GeckoAppShell$1.reportException(GeckoAppShell.java:187)
    at org.mozilla.gecko.CrashHandler.uncaughtException(CrashHandler.java:428)
    at org.mozilla.gecko.GeckoAppShell$1.uncaughtException(GeckoAppShell.java:162)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
    at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

**Comment by snorp** [comment]
Hi, thanks for the report! We are tracking this issue in Bugzilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1529082

**Comment by ifmvo** [comment]
Thank you, but my app is not able to update the version on GooglePlay because of this issue, I am eager to give me some advice.

**Comment by snorp** [comment]
For now I think you'll need to either stop using GeckoView or App Bundles until the issue is fixed (which may be a while).
